QuanLyVT/Controllers/ThongKeThietBiController.cs
using QuanLyVT.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyVT.Controllers
{
    public class ThongKeThietBiController : Controller
    {
        private Model1 db = new Model1();
        //GET: ThongKeThietBi
        public ActionResult Index()
        {
            return View();
        }
        // à tao biêết rồi tháấy koo cái đó 


        public ActionResult ThongKeTB()
        {
            ViewBag.ID_THIET_BI = new SelectList(db.THIET_BI, "ID_THIET_BI", "Ten_TB");
            ViewBag.ID_HOP_DONG = new SelectList(db.HOP_DONG, "ID_HOP_DONG", "Ten_HD");
            return View();
        }
        public ActionResult ViewThongKe(int? ID_THIET_BI, int? ID_HOP_DONG)
        {
            if(ID_THIET_BI != null || ID_HOP_DONG != null)
            {
                if(ID_THIET_BI != null && ID_HOP_DONG == null)
                {
                    if (ID_THIET_BI != null)
                    {
                        ViewBag.checkTBorHD = "ThietBi";
                        var list = db.Database.SqlQuery<modelThongKe>("ThongKeTheoThietBi @idThietBi", new SqlParameter("@idThietBi", (int?)ID_THIET_BI)).ToList();
                        return View(list);
                    }
                }    
                else if(ID_HOP_DONG != null && ID_THIET_BI == null)
                {
                    if (ID_HOP_DONG != null)
                    {
                        ViewBag.checkTBorHD = "HopDong";
                        var listhd = db.Database.SqlQuery<modelThongKe>("ThongKeTheoHopDong @idHopDong", new SqlParameter("@idHopDong", (int?)ID_HOP_DONG)).ToList();
                        return View(listhd);
                    }
                }
                else if (ID_THIET_BI != null && ID_HOP_DONG != null)
                {
                    TempData["ResultMessage"] = "Vui lòng chọn thống kê theo thiết bị hoặc thống kê theo hợp đồng!";
                    return RedirectToAction("ThongKeTB");
                }
                else
                {
                    TempData["ResultMessage"] = "Có lỗi trong quá trình thống kê. Vui lòng thử lại sau!";
                    return RedirectToAction("ThongKeTB");
                }
            } 
            else
            {
                TempData["ResultMessage"] = "Vui lòng chọn kiểu thống kê!";
                return RedirectToAction("ThongKeTB");
            }
            return View();
        }
    }
}

QuanLyVT/Views/ThongKeThietBi/ThongKeTB.cshtml
@model  QuanLyVT.Models.THIET_BI
@{
    ViewBag.Title = "ThongKeTB";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5><b>Trang chủ / Thống kê</b></h5>
<br />
<h2 style="text-align: center">Thống kê </h2>

@using (Html.BeginForm("ViewThongKe", "ThongKeThietBi", FormMethod.Get)) // -- phần thay đổi
{
    <div class="col-md-12">
        <label>Từ ngày</label>
        <input type="date" id="tungay" name="tungay" />
        <label style="margin-left:100px">Đến ngày</label>
        <input type="date" id="dengay" name="dengay"/>
    </div>
    <div class="form-group">
        <label class="col-md-3" style="margin-top:10px">Thống kê theo thiết bị</label>
        <div class="col-md-9">
            @Html.DropDownList("ID_THIET_BI", null, "------Chọn thiết bị------", htmlAttributes: new { @class = "form-control", @style = " margin: 5px" })

        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3" style="margin-top:10px">Thống kê theo hợp đồng</label>
        <div class="col-md-9">
            @Html.DropDownList("ID_HOP_DONG", null, "------Chọn hợp đồng------", htmlAttributes: new { @class = "form-control", @style = " margin: 5px" })

        </div>
    </div>
    


    <button type="submit" class="btn btn-info btn-sm" style="margin-left:650px"><b>Thống kê</b></button>
    if (TempData["ResultMessage"] != null)
    {
        <h5 style="color: red; margin-left: 500px">@TempData["ResultMessage"]</h5>
    }
}

QuanLyVT/Views/ThongKeThietBi/ViewThongKe.cshtml
@model List<QuanLyVT.Models.modelThongKe>

@{
    ViewBag.Title = "ViewThongKe";
    Layout = "~/Views/Shared/_Layout.cshtml";


}

@if (ViewBag.checkTBorHD == "ThietBi")
{
    <h5><b>Trang chủ / Thống kê thiết bị</b></h5>
    <br />
    <h2 style="text-align: center">Thống kê theo thiết bị</h2>


    <table id="myTable" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Mã thiết bị
                </th>
                <th>
                    Tên thiết bị
                </th>
                <th>
                    Hợp đồng
                </th>
                <th>
                    Gói thầu
                </th>

                <th>
                    Bện viện/ đối tác
                </th>
                <th>
                    Người phụ trách
                </th>
                <th>
                    Nhân viên kỹ thuật
                </th>
                <th>
                    Xuất xứ
                </th>
                <th>
                    Năm sản xuất
                </th>
                
            </tr>
        </thead>
        <tbody>
            @if (Model.Count > 0)
            {

                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ma_TB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_TB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TEN_HD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_Goi_Thau)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_BV)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_Nguoi_Phu_Trach)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_NV_KT)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.XX_TC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nam_SX)
                        </td>
                       

                    </tr>
                }


            }
        </tbody>
    </table>
}
else
{
    <h5><b>Trang chủ / Thống hợp đồng</b></h5>
    <br />
    <h2 style="text-align: center">Thống kê theo hợp đồng</h2>


    <table id="myTable" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Mã hợp đồng
                </th>
                <th>
                    Tên hợp đồng
                </th>
                <th>
                    Thiết bị
                </th>
                <th>
                    Gói thầu
                </th>

                <th>
                    Bện viện/ đối tác
                </th>
                <th>
                    Người phụ trách
                </th>
                <th>
                    Nhân viên kỹ thuật
                </th>
                <th>
                    Ngày hoàn thành
                </th>
                <th>
                    Hạn bảo hành
                </th>
                <th>
                    Số lượng thiết bị
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count > 0)
            {

                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ma_HD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TEN_HD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_TB)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_Goi_Thau)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_BV)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_Nguoi_Phu_Trach)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ten_NV_KT)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ngay_Hoan_Thanh)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Han_BH)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.So_Luong)
                        </td>

                    </tr>
                }


            }
        </tbody>
    </table>
}


<button class="btn btn-error" style="color: white">
    @Html.ActionLink("Quay lại", "ThongKeTB", new { @class = "btn btn-warning", Styles = "color:white !important" })
</button>

QuanLyVT/Views/ThongKeThietBi/ViewThongKeHD.cshtml
@model List<QuanLyVT.Models.modelHopDong>
@{
    ViewBag.Title = "ViewThongKeHD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">Thống kê theo hợp đồng</h2>


<table id="myTable" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Mã hợp đồng
            </th>
            <th>
                Tên hợp đồng
            </th>
            <th>
               Thiết bị
            </th>
            <th>
                Gói thầu
            </th>

            <th>
                Bện viện/ đối tác
            </th>
            <th>
                Người phụ trách
            </th>
            <th>
                Nhân viên kỹ thuật
            </th>
            <th>
                Ngày hoàn thành
            </th>
            <th>
                Hạn bảo hành
            </th>

        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {

            foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ma_HD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TEN_HD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_TB)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Ten_Goi_Thau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_BV)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Ten_Nguoi_Phu_Trach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_NV_KT)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngay_Hoan_Thanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Han_BH)
            </td>


        </tr>
            }


        }
    </tbody>
</table>

<button class="btn btn-error" style="color: white">
    @Html.ActionLink("Quay lại", "ThongKeTB", new { @class = "btn btn-warning", Styles = "color:white !important" })
</button>